# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_xlconcat_0/design_1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_0 || ORIG_REF_NAME==design_1_axi_gpio_3_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_0 || ORIG_REF_NAME==design_1_axi_timer_0_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_fit_timer_0_0/design_1_fit_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fit_timer_0_0 || ORIG_REF_NAME==design_1_fit_timer_0_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_emc_0_0/design_1_axi_emc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_emc_0_0 || ORIG_REF_NAME==design_1_axi_emc_0_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: C:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_DiceNumberGeneratorC_0_0/design_1_DiceNumberGeneratorC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DiceNumberGeneratorC_0_0 || ORIG_REF_NAME==design_1_DiceNumberGeneratorC_0_0} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_8 || ORIG_REF_NAME==design_1_auto_pc_8} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_6 || ORIG_REF_NAME==design_1_auto_pc_6} -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_7 || ORIG_REF_NAME==design_1_auto_pc_7} -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_0 || ORIG_REF_NAME==design_1_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_0 || ORIG_REF_NAME==design_1_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_0 || ORIG_REF_NAME==design_1_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_emc_0_0/design_1_axi_emc_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_emc_0_0 || ORIG_REF_NAME==design_1_axi_emc_0_0} -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_emc_0_0/design_1_axi_emc_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_emc_0_0 || ORIG_REF_NAME==design_1_axi_emc_0_0} -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_emc_0_0/design_1_axi_emc_0_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7_ooc.xdc

# XDC: c:/Users/ASUS/OneDrive - Universidade de Aveiro/Joo Abrantes/UAveiro/6Ano/CR/DMA/project_DMA/project_DMA.gen/sources_1/bd/design_1/design_1_ooc.xdc
